import { state } from '../state.js';
import { esc, safeUrl } from '../utils.js';
import { buildOrgIndex, resolveNames } from '../compute/orgLookup.js';

// Reference Files tab — a flat, unfiltered table of supporting files from the optional
// "Reference Files" Excel sheet. File Name links to its URL/Path (sanitized); Generated By
// resolves to a Team via the org chart and is flagged if the person isn't defined.
export function renderReferenceFiles() {
  const body = document.getElementById('reference-body');
  if (!body) return;

  const files = state.ProjectData.referenceFiles || [];
  if (!files.length) {
    body.innerHTML = `<div style="display:flex;flex-direction:column;align-items:center;justify-content:center;
      padding:60px 20px;gap:12px;color:var(--muted);text-align:center">
      <div style="font-size:2rem">📎</div>
      <div style="font-weight:700;color:var(--text)">No reference files</div>
      <div style="font-size:0.83rem">Add a <code>Reference Files</code> sheet to your Excel
        (File Name, URL/Path, Generated Date, Generated By, Notes).</div>
    </div>`;
    return;
  }

  const orgIndex = buildOrgIndex(state.ProjectData.org);
  const rows = files.map(f => {
    const res  = resolveNames(f.generatedBy, orgIndex);
    const href = safeUrl(f.url);
    const nameCell = href
      ? `<a href="${esc(href)}" target="_blank" rel="noopener noreferrer">${esc(f.fileName)}</a>`
      : esc(f.fileName || '—');
    const byAttrs = res.hasUnknown
      ? ` class="sr-invalid" title="Person not defined in org chart" aria-label="${esc(f.generatedBy)} — person not defined in org chart"`
      : '';
    const byWarn = res.hasUnknown ? ' <span class="sr-warn" aria-hidden="true">⚠</span>' : '';
    return `<tr>
      <td>${nameCell}</td>
      <td style="color:var(--muted)">${esc(f.generatedDate || '—')}</td>
      <td${byAttrs}>${esc(f.generatedBy || '—')}${byWarn}</td>
      <td style="color:var(--muted)">${esc(res.teams.join(', ') || '—')}</td>
      <td style="color:var(--muted);max-width:320px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap"
        title="${esc(f.notes || '')}">${esc(f.notes || '—')}</td>
    </tr>`;
  }).join('');

  body.innerHTML = `
    <table class="status-table" role="table" aria-label="Reference Files">
      <thead><tr role="row">
        <th>File Name</th><th>Generated Date</th><th>Generated By</th><th>Team</th><th>Notes</th>
      </tr></thead>
      <tbody>${rows}</tbody>
    </table>`;
}
