// Name → team resolution and org-chart validation for the POC / Customer / "Generated By"
// fields. Pure (no DOM, no state import) so it stays unit-testable.
//
// Matching is trim + case-insensitive. When the org chart is empty, validation is skipped
// entirely (nothing is flagged) — see resolveNames().

function norm(name) {
  return String(name == null ? '' : name).trim().toLowerCase();
}

/**
 * Build a lookup index from the org array.
 * @param {Array<{name:string, team:string}>} org
 * @returns {Map<string,string>} normalized name → team (first wins on duplicate names)
 */
export function buildOrgIndex(org) {
  const idx = new Map();
  (org || []).forEach(p => {
    const key = norm(p && p.name);
    if (key && !idx.has(key)) idx.set(key, (p && p.team) || '');
  });
  return idx;
}

/**
 * Resolve a comma-separated list of names against the org index.
 * @param {string} rawCsv - e.g. "Alice, Bob"
 * @param {Map<string,string>} orgIndex - from buildOrgIndex()
 * @returns {{names:string[], teams:string[], unknown:string[], hasUnknown:boolean}}
 *   - names: cleaned individual names (trimmed, blanks dropped)
 *   - teams: unique non-empty teams of the found names, in input order
 *   - unknown: names not present in the org (always [] when org is empty → validation skipped)
 *   - hasUnknown: true if any name was unknown (false when validation is skipped)
 */
export function resolveNames(rawCsv, orgIndex) {
  const names = String(rawCsv == null ? '' : rawCsv)
    .split(',').map(s => s.trim()).filter(Boolean);
  const validate = orgIndex instanceof Map && orgIndex.size > 0;
  const teams = [];
  const unknown = [];
  names.forEach(n => {
    const team = validate ? orgIndex.get(norm(n)) : undefined;
    if (team === undefined) {
      if (validate) unknown.push(n);
    } else if (team && !teams.includes(team)) {
      teams.push(team);
    }
  });
  return { names, teams, unknown, hasUnknown: unknown.length > 0 };
}
